from pathlib import Path
import json,hashlib,subprocess
base=Path(__file__).resolve().parents[1]
entries=[]
def add(id,title,authors,year,venue,url,pdf_url,local,relevance,verification,limitations,**kw):
 d=dict(id=id,title=title,authors=authors,year=year,venue=venue,url=url,pdf_url=pdf_url,local_file=local,relevance=relevance,verification=verification,limitations=limitations,accessed='2026-09-25',**kw)
 if local:
  p=base/'papers'/local
  assert p.read_bytes().startswith(b'%PDF')
  d['sha256']=hashlib.sha256(p.read_bytes()).hexdigest();d['bytes']=p.stat().st_size
  info=subprocess.run(['pdfinfo',str(p)],capture_output=True,text=True).stdout
  d['pages']=int(next(x.split(':')[1].strip() for x in info.splitlines() if x.startswith('Pages:')))
 entries.append(d)
add('roma2020','ROMA: Multi-Agent Reinforcement Learning with Emergent Roles',['Tonghan Wang','Heng Dong','Victor Lesser','Chongjie Zhang'],2020,'ICML / PMLR 119:9876–9886','https://proceedings.mlr.press/v119/wang20f.html','https://proceedings.mlr.press/v119/wang20f/wang20f.pdf','2020_ROMA_Wang_Emergent_Roles.pdf','Essential baseline: dynamic stochastic role embeddings and role-conditioned policies.','Publisher record and full primary PDF; Eqs 1–7 and Sec5.1 checked.','Health/death adaptation is demonstrated; unseen entrant/capability-distribution recovery not established by audited experiments.',additional_files=[dict(local_file='2020_ROMA_Wang_Supplement.pdf',pdf_url='https://proceedings.mlr.press/v119/wang20f/wang20f-supp.pdf',verification='Supplement Appendix A.1 checked; contains variational derivation.')])
add('rode2021','RODE: Learning Roles to Decompose Multi-Agent Tasks',['Tonghan Wang','Tarun Gupta','Anuj Mahajan','Bei Peng','Shimon Whiteson','Chongjie Zhang'],2021,'ICLR 2021','https://openreview.net/forum?id=TTUVg6vkNjK','https://anuj-mahajan.github.io/files/rode.pdf','2021_RODE_Wang_Roles_Decompose_Tasks_Author_Final.pdf','Learned roles and frozen role-policy transfer to larger teams; major novelty boundary.','Official venue record and author-hosted final primary PDF checked, Sec4.3 pp8–9/Fig5/App C.2.','Transfer learns a new action encoder using 50k target-task samples, so not zero adaptation of all parameters.',additional_files=[dict(local_file='2021_RODE_Wang_Roles_Decompose_Tasks.pdf',pdf_url='https://arxiv.org/pdf/2010.01523',verification='Earlier preprint; pagination differs; prefer author final for claims.')])
add('nguyen2022roletransfer','Learning to Transfer Role Assignment Across Team Sizes',['Dung Nguyen','Phuoc Nguyen','Svetha Venkatesh','Truyen Tran'],2022,'AAMAS 2022','https://arxiv.org/abs/2204.12937','https://arxiv.org/pdf/2204.12937','2022_Nguyen_Transfer_Role_Assignment_Team_Sizes.pdf','Role-based variable-size mixing and curriculum transfer.','Author arXiv record says accepted AAMAS2022; primary PDF Sec3.1–3.3 checked.','Larger teams continue training; not pure frozen deployment. Agent-to-role mixer weights normalize over agents.')
add('sora2023','SORA: Improving Multi-agent Cooperation with a Soft Role Assignment Mechanism',['Guangchong Zhou','Zhiwei Xu','Zeren Zhang','Guoliang Fan'],2023,'ICONIP 2023 / LNCS 14447:319–331 (print/citation year 2024)','https://link.springer.com/chapter/10.1007/978-981-99-8079-6_25','https://link.springer.com/content/pdf/10.1007/978-981-99-8079-6_25.pdf',None,'Precedent for soft role assignment and role-specific Q networks.','Publisher abstract, author list, date and Crossref metadata verified.','Full text unavailable through public routes; PDF endpoint returned HTML. Exact Q aggregation or probability-mixture equation not verified.',publication_dates={'first_online':'2023-11-14','print_year':2024})
add('roco2026','ROCO: Role-oriented communication for efficient multi-agent reinforcement learning',['Zaipeng Xie','Sitong Shen','Yaowu Wang','Chentai Qiao','Bin Tang','Wenzhan Song'],2026,'Expert Systems with Applications 297,129421','https://www.sciencedirect.com/science/article/pii/S0957417425030374','https://www.sciencedirect.com/science/article/pii/S0957417425030374/pdfft',None,'Close overlap: learned roles plus inter-role and intra-role communication.','Publisher previews, author site, author code repository and Crossref metadata verified.','Publisher and SSRN PDF attempts blocked (403); exact equations and transfer protocol not fully verified. Larger benchmark sizes do not alone prove transfer.',doi='10.1016/j.eswa.2025.129421',publication_dates={'issue':'2026-02','doi_created':'2025-08-21','preprint_posted':'2024-12-16'},author_preprint_url='https://ssrn.com/abstract=5060074',code_url='https://github.com/surebo/ROCO')
add('grdc2026','GRDC: A Unified Graph-Driven Framework for Role Discovery and Communication in Multi-Agent Reinforcement Learning',['Zihong Gao','Hongjian Liang','Yuanhui Hao','Lei Hao','Liangjun Ke'],2026,'AAAI 40(35):29441–29449','https://ojs.aaai.org/index.php/AAAI/article/view/40185','https://ojs.aaai.org/index.php/AAAI/article/download/40185/44146','2026_GRDC_Gao_Role_Discovery_Communication.pdf','Prototype roles from graph interactions with same-role-only communication.','Publisher record and full PDF method pp3–4 checked.','No frozen capability-loss recovery guarantee; claimed linear complexity depends on bounded neighborhood and role-group sizes.',doi='10.1609/aaai.v40i35.40185')
add('scout2026','SCoUT: Scalable Communication via Utility-Guided Temporal Grouping in Multi-Agent Reinforcement Learning',['Manav Vora','Gokul Puthumanaillam','Hiroyasu Tsukamoto','Melkior Ornik'],2026,'arXiv preprint 2603.04833v1','https://arxiv.org/abs/2603.04833','https://arxiv.org/pdf/2603.04833','2026_SCoUT_Vora_Temporal_Grouping.pdf','Soft assignments jointly guide recipient learning and group critic; counterfactual message utility.','Author arXiv record and full PDF Sec4.2–4.6 checked.','Group sampler is discarded at execution. Large population training is not small-to-large zero-shot evidence. Peer-reviewed venue not verified.')
add('gira2026','Scalable multi-agent reinforcement learning with group interaction-based role adaptation',['Shiwei Li','Mengke Wang','Tao Wang','Xiangfeng Luo','Shaorong Xie'],2026,'Neurocomputing 700,134437','https://www.sciencedirect.com/science/article/pii/S0925231226018357','https://www.sciencedirect.com/science/article/pii/S0925231226018357/pdfft',None,'Direct overlap on interaction-derived roles, joining/leaving agents, unseen-size generalization.','Primary publisher abstract, introduction, method/experiment previews and Crossref metadata verified.','Full PDF blocked (403). Homogeneous shared-observation/action-space scope. Detailed churn schedule, equations and test protocol remain unchecked.',doi='10.1016/j.neucom.2026.134437',publication_dates={'issue':'2026-11','doi_created':'2026-07-07','record_accessible_by':'2026-09-25'})
add('gpl2021','Towards Open Ad Hoc Teamwork Using Graph-based Policy Learning',['Arrasy Rahman','Niklas Höpner','Filippos Christianos','Stefano V. Albrecht'],2021,'ICML / PMLR 139:8776–8786','https://proceedings.mlr.press/v139/rahman21a.html','https://proceedings.mlr.press/v139/rahman21a/rahman21a.pdf','2021_GPL_Rahman_Open_Ad_Hoc_Teamwork.pdf','Agent entry/exit, recurrent teammate-type inference and graph value generalization.','Publisher/author records and primary PDF Sec3–5 checked.','Single controlled learner with fixed-policy teammates, not jointly trained full team. GNN generalization results empirical.')
add('gpl2023','A General Learning Framework for Open Ad Hoc Teamwork Using Graph-based Policy Learning',['Arrasy Rahman','Ignacio Carlucho','Niklas Höpner','Stefano V. Albrecht'],2023,'JMLR 24(298):1–74','https://jmlr.org/papers/v24/22-099.html','https://jmlr.org/papers/volume24/22-099/22-099.pdf','2023_GPL_Rahman_General_Open_Ad_Hoc_Framework.pdf','Partial-observability extension with belief over existence, state and teammate type.','JMLR record and full PDF available; formulation and belief sections checked.','74-page paper selectively audited; all experiments and derivations not independently reproduced. Single-learner ad hoc setting.')
add('ciao2024','Open Ad Hoc Teamwork with Cooperative Game Theory',['Jianhong Wang','Yang Li','Yuan Zhang','Wei Pan','Samuel Kaski'],2024,'ICML / PMLR 235:50902–50930','https://proceedings.mlr.press/v235/wang24an.html','https://raw.githubusercontent.com/mlresearch/v235/main/assets/wang24an/wang24an.pdf','2024_CIAO_Wang_Open_Ad_Hoc_Cooperative_Game_Theory.pdf','Theoretical open-team value decomposition and coalitional-affinity formulation.','Primary publisher record and PDF Theorem2 and AppendixD assumptions checked.','Theorem requires specified reward structure/departure assumptions; AppendixD Assumption7 assumes GNN generalizability to agent types.')
add('naht2024','N-agent Ad Hoc Teamwork',['Caroline Wang','Arrasy Rahman','Ishan Durugkar','Elad Liebman','Peter Stone'],2024,'NeurIPS 37','https://proceedings.nips.cc/paper_files/paper/2024/hash/cabf611498431ad89a85ace75f790d93-Abstract-Conference.html','https://proceedings.neurips.cc/paper_files/paper/2024/file/cabf611498431ad89a85ace75f790d93-Paper-Conference.pdf','2024_NAHT_Wang_N_Agent_Ad_Hoc_Teamwork.pdf','Multiple controlled agents with varying uncontrolled teammate policies; POAM.','Proceedings record and PDF Sec3–6 checked.','Composition sampler runs at episode start; should not be cited as proof of within-episode churn handling.')
add('matnaht2025','Sequence Modeling for N-Agent Ad Hoc Teamwork',['Caroline Wang','Di Yang Shi','Elad Liebman','Ishan Durugkar','Arrasy Rahman','Peter Stone'],2025,'arXiv preprint 2506.05527v3','https://arxiv.org/abs/2506.05527','https://arxiv.org/pdf/2506.05527','2025_MAT_NAHT_Sequence_Modeling.pdf','Transformer sequence modeling for variable controlled subteams.','Author arXiv metadata and primary PDF abstract/method checked.','Centralized method; single StarCraft task in inspected preprint; no claimed decentralized latent capability recovery. Venue status not independently verified.',version_date='2025-10-19')
add('shapleymachine2025','Shapley Machine: A Game-Theoretic Framework for N-Agent Ad Hoc Teamwork',['Jianhong Wang','Yang Li','Samuel Kaski','Jonathan Lawry'],2025,'arXiv preprint 2506.11285v1','https://arxiv.org/abs/2506.11285','https://arxiv.org/pdf/2506.11285','2025_Shapley_Machine_N_Agent_Ad_Hoc.pdf','Cooperative-game credit assignment for open controlled subsets.','Author record and primary PDF abstract/method checked.','Proofs and all experiments not deeply audited; not a role-aware communication result. Venue status not independently verified.')
add('findik2024','Collaborative Adaptation for Recovery from Unforeseen Malfunctions in Discrete and Continuous MARL Domains',['Yasin Findik','Hunter Hasenfus','Reza Azadeh'],2024,'IEEE Conference on Decision and Control (CDC)','https://cs.uml.edu/~reza/pdf/CDC_2024.pdf','https://cs.uml.edu/~reza/pdf/CDC_2024.pdf','2024_Findik_Collaborative_Adaptation_Malfunctions.pdf','Direct capability-malfunction recovery precedent.','Author-hosted conference PDF verified; SecVI and post-failure training protocol checked.','Assumes malfunction detection/identity and continued learning; not frozen policy recovery. Author-site certificate chain required public curl insecure mode for download.')
add('plato2026','PLATO: Pointer Learner for Agent and Task Openness',['Alireza Saleh Abadi','Leen-Kiat Soh','Daniel Alan Redder','Adam Eck','Prashant Doshi'],2026,'arXiv preprint 2607.25082v2','https://arxiv.org/abs/2607.25082','https://arxiv.org/pdf/2607.25082','2026_PLATO_Agent_Task_Openness.pdf','Open agents/tasks, pointer actor, graph critic, zero-shot evaluation and symmetry analysis.','Author metadata, primary PDF Sec2 and Lemma1/Theorem1 checked.','Fundamental openness including capability changes left future work. Well-definedness/symmetry theorem is not a return-generalization guarantee.',version_date='2026-07-29')
add('submapg2026','Submodular Multi-Agent Policy Learning for Online Distributed Task Allocation in Open Multi-Agent Systems',['Jing Liu','Yangyang Yang','Luca Ballotta','Fangfei Li','Yang Tang','Ruggero Carli'],2026,'arXiv preprint 2605.13269v1','https://arxiv.org/abs/2605.13269','https://arxiv.org/pdf/2605.13269','2026_SubMAPG_Submodular_Open_Team_Allocation.pdf','Theorem-backed open-team allocation under monotone submodular utilities.','Author record, primary PDF Lemmas3.1–3.2 and Theorems5.1–5.2 scope checked.','Guarantees concern projected marginal-space ascent, not arbitrary neural actor updates or full long-horizon policy optimality. Complementary sensing/capture reward may violate submodularity.')
entries.append({'id': 'gmat2026', 'title': 'Learning group collaboration for efficient multi-agent reinforcement learning', 'authors': ['Qide Wang', 'Daxin Liu', 'Zhenyu Liu', 'Jianrong Tan'], 'year': 2026, 'venue': 'Knowledge-Based Systems 351,116612', 'url': 'https://www.sciencedirect.com/science/article/pii/S0950705126013389', 'pdf_url': 'https://www.sciencedirect.com/science/article/pii/S0950705126013389/pdfft', 'local_file': None, 'relevance': 'Role-guided grouping, compressed within-group and cross-group communication in an autoregressive multi-agent transformer.', 'verification': 'Primary publisher abstract, introduction and methodology preview; Crossref author/title/volume/date/DOI metadata checked.', 'limitations': 'Publisher PDF returned HTTP403; no legal public author copy found in targeted search. Exact equations, execution decentralization, and entry/exit/capability-recovery experiments not verified.', 'accessed': '2026-09-25', 'doi': '10.1016/j.knosys.2026.116612', 'publication_dates': {'issue': '2026-10', 'doi_created': '2026-07-11'}})
for d in entries:
 if d['id']=='findik2024': d['doi']='10.1109/CDC56724.2024.10885831'
 for a in d.get('additional_files',[]):
  p=base/'papers'/a['local_file'];a['sha256']=hashlib.sha256(p.read_bytes()).hexdigest();a['bytes']=p.stat().st_size
out=base/'papers'/'manifest_roles.json';out.write_text(json.dumps({'audit_date':'2026-09-25','scope':'Learned roles, dynamic and open teams, capability-malfunction recovery; complements other manifests.','papers':entries},indent=2,ensure_ascii=False)+'\n')
print('Wrote',len(entries),'paper records;',sum(d['local_file'] is not None for d in entries),'main PDFs;',sum(len(d.get('additional_files',[])) for d in entries),'additional PDF versions/supplements;',sum(d['local_file'] is None for d in entries),'unavailable full texts')
